extends Node

func _ready() -> void:
	call_deferred("verify")

func verify() -> void:
	var packed: PackedScene = load("res://pipeline/pipeline_fixture.glb")
	assert(packed != null, "GLB did not import as PackedScene")
	var instance: Node3D = packed.instantiate()
	add_child(instance)
	assert(instance.transform.is_equal_approx(Transform3D.IDENTITY))
	var body: MeshInstance3D = instance.find_child("MeterBody", true, false)
	var pivot: Node3D = instance.find_child("ControlPivot", true, false)
	var lever: MeshInstance3D = instance.find_child("PivotLever", true, false)
	assert(body != null and pivot != null and lever != null)
	assert(body.mesh.get_aabb().size.distance_to(Vector3(0.6, 0.2, 1.0)) < 0.000001)
	assert(lever.mesh.get_aabb().size.distance_to(Vector3(0.04, 0.04, 0.3)) < 0.000001)
	assert(body.global_transform.is_equal_approx(Transform3D.IDENTITY))
	assert(pivot.position.distance_to(Vector3(0.2, 0.1, -0.3)) < 0.000001)
	assert(lever.get_parent() == pivot)
	assert(lever.position.distance_to(Vector3(0, 0, -0.15)) < 0.000001)
	var material: StandardMaterial3D = body.mesh.surface_get_material(0)
	assert(material != null and material.resource_name == "ProofBlue")
	assert(abs(material.roughness - 0.8) < 0.000001 and material.metallic == 0.0)
	assert(lever.mesh.surface_get_material(0) == material)
	# glTF's base color factors are linear; Godot exposes material colors in sRGB.
	var expected_color: Color = Color(0.04, 0.18, 0.6, 1.0).linear_to_srgb()
	assert(abs(material.albedo_color.r - expected_color.r) < 0.000001)
	assert(abs(material.albedo_color.g - expected_color.g) < 0.000001)
	assert(abs(material.albedo_color.b - expected_color.b) < 0.000001)
	var player: AnimationPlayer = instance.find_child("AnimationPlayer", true, false)
	assert(player != null and player.has_animation("PivotSweep"))
	assert(abs(player.get_animation("PivotSweep").length - 1.0) < 0.000001)
	player.play("PivotSweep")
	player.seek(0.0, true)
	assert(abs(pivot.rotation.y) < 0.000001)
	var observed_angles: Array[float] = [pivot.rotation.y]
	player.seek(0.5, true)
	assert(abs(pivot.rotation.y - 0.25) < 0.000001)
	observed_angles.append(pivot.rotation.y)
	var midpoint: Vector3 = pivot.position + Basis(Vector3.UP, 0.25) * Vector3(0, 0, -0.15)
	assert(lever.global_position.distance_to(midpoint) < 0.000001)
	player.seek(1.0, true)
	assert(abs(pivot.rotation.y - 0.5) < 0.000001)
	observed_angles.append(pivot.rotation.y)
	var expected: Vector3 = pivot.position + Basis(Vector3.UP, 0.5) * Vector3(0, 0, -0.15)
	assert(lever.global_position.distance_to(expected) < 0.000001)
	print("GLB_IMPORT_PROOF " + JSON.stringify({"passed": true, "engine": Engine.get_version_info(), "animation": "PivotSweep", "length_s": player.get_animation("PivotSweep").length, "rotation_samples_rad": observed_angles, "material": material.resource_name, "albedo_color_srgb": [material.albedo_color.r, material.albedo_color.g, material.albedo_color.b], "dimensions_m": [body.mesh.get_aabb().size.x, body.mesh.get_aabb().size.y, body.mesh.get_aabb().size.z], "scope": "actual Godot resource import/transforms/material only; no GPU or aircraft fidelity"}))
	instance.queue_free()
	await get_tree().process_frame
	get_tree().quit(0)
