import fs from 'node:fs';

const check = process.argv.includes('--check');
const backlog = JSON.parse(fs.readFileSync('docs/backlog.json', 'utf8'));
const roadmap = fs.readFileSync('docs/roadmap.md', 'utf8');
const issueIndex = fs.existsSync('docs/issue-index.md') ? fs.readFileSync('docs/issue-index.md','utf8') : '';
const numbers = new Map([...issueIndex.matchAll(/^\| ([A-Z0-9-]+) \| \[#(\d+)/gm)].map(x=>[x[1],x[2]]));
const issueLink = (key, fallback) => numbers.has(key) ? `https://github.com/${backlog.repository}/issues/${numbers.get(key)}` : fallback;
const outputs = new Map();
const sources = ['product.md', 'experience-and-progress.md', 'realism-and-validation.md', 'training-and-safety.md', 'world-and-data.md'];
const requirements = new Map();
for (const file of sources) {
  const text = fs.readFileSync(`docs/${file}`, 'utf8');
  for (const match of text.matchAll(/\b(?:PRD|UX|REAL|SAFE|WORLD)-\d{3}\b/g)) {
    if (!requirements.has(match[0])) requirements.set(match[0], file);
  }
}
let trace = '# Requirement traceability\n\nGenerated by `node tools/render-plan.mjs` from the five requirement documents and [backlog.json](backlog.json). References identify planned coverage, not completed validation. All requirements need their own acceptance evidence even where several share a task.\n\n| Requirement | Specification | Planned issues |\n|---|---|---|\n';
for (const [id, file] of [...requirements].sort()) {
  const tasks = backlog.issues.filter(x => x.requirements.includes(id));
  trace += `| ${id} | [${file}](${file}) | ${tasks.map(x => `[${x.key}](${issueLink(x.key,'issue-index.md')})`).join(', ') || '**UNMAPPED**'} |\n`;
}
outputs.set('docs/requirements.md', trace);
const slugs = ['p0-foundations','p1-flight-core','p2-first-flight','p3-complete-circuit','p4-region-and-weather','p5-training-and-atc','p6-realism-and-failures','p7-windows-release','p8-expansion'];
let phaseIndex = '# Phase dispatch briefs\n\nRead the assigned phase brief alongside its GitHub issue, [contracts](../contracts.md), and [agent operations](../agent-operations.md). These generated briefs extract the canonical [roadmap](../roadmap.md); they do not change any gate.\n\n';
for (const [i, phase] of backlog.milestones.entries()) {
  const key = `P${i}`;
  const section = roadmap.match(new RegExp(`^## ${key} [^\\n]+\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, 'm'))?.[1]?.trim();
  if (!section) throw new Error(`Missing roadmap section ${key}`);
  const work = backlog.issues.filter(x=>x.phase===key && x.kind!=='epic');
  let text = `# ${phase.title}\n\nGenerated from [roadmap](../roadmap.md) and [backlog](../backlog.json). Consult the [issue index](../issue-index.md) for actual GitHub links.\n\n${section}\n\n## Dispatch queue\n\n| Task | Area | Dependencies | Owned paths |\n|---|---|---|---|\n`;
  for (const item of work) text += `| [${item.key}](${issueLink(item.key,'../issue-index.md')}) — ${item.title} | ${item.labels.find(x=>x.startsWith('area:')).slice(5)} | ${item.depends_on.join(', ') || 'Owner review'} | ${item.owned_paths.map(x=>'`'+x+'`').join(', ')} |\n`;
  text += '\n## Agent handoff\n\nUse the canonical issue acceptance/evidence fields. Claim one task with an isolated branch/worktree; coordinate shared paths before editing. Publish interface changes first, then consumers. Record build/content/source versions, test outputs, unresolved gaps and human-review status in the PR. Prepare `docs/evidence/'+key+'/` gate report only after the integrated scenario is actually run. The integrator changes dependency status labels; agents do not self-certify human pilot or owner review.\n';
  outputs.set(`docs/phases/${slugs[i]}.md`, text);
  phaseIndex += `- [${phase.title}](${slugs[i]}.md)\n`;
}
outputs.set('docs/phases/README.md', phaseIndex);
let mismatch = false;
for (const [file, content] of outputs) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file,'utf8').replaceAll('\r\n','\n') !== content) { console.error(`Stale generated plan: ${file}`); mismatch = true; }
  } else {
    fs.mkdirSync(file.slice(0,file.lastIndexOf('/')), { recursive: true });
    fs.writeFileSync(file, content);
  }
}
if (mismatch) process.exitCode = 1;
else console.log(`${check?'Checked':'Rendered'} ${requirements.size} requirements and ${backlog.milestones.length} phase dispatch briefs.`);
